### ISSUE TITLE
Dummies show up on radio backpack

### ISSUE THREAD

**Issue by private-tristan** [PvE-CMSS13/PvE-CMSS13#84]
### Testmerges

[#64: 'Hotfix canmove' by morrowwolf at commit 84db018ff2](https://github.com/PvE-CMSS13/PvE-CMSS13/pull/64)
[#72: 'Projectile smooth movement' by Doubleumc at commit 52c021137b](https://github.com/PvE-CMSS13/PvE-CMSS13/pull/72)

### Round ID

229 on red

### Description of the bug

![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/54422837/471db2c7-6959-4312-919a-c66ec1f27d6a)

### What's the difference with what should have happened?

they shouldn't be there

### How do we reproduce this bug?

1. get radio backpack
2. go to marine section
3. look
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
Do they have radio backpacks on

**Comment by FslashN** [comment]
I've tested this today locally and remote and it's no longer an issue. Could have been a mapping change that fixed it, but the dummies no longer show up in the call menu.

**Comment by FslashN** [comment]
I've tested this today locally and remote and it's no longer an issue. Could have been a mapping change that fixed it, but the dummies no longer show up in the call menu.

**Comment by FslashN** [comment]
I've tested this locally and remote, and it does not appear to be an issue anymore. Tested both the rotary phones and the radio pack.
